<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LAPTOP-A11EL1IC" name="attribute.timeout" tests="3" failures="0" timestamp="09 Feb 2020 15:47:10 GMT" time="0.297" errors="1">
  <testcase name="testcaes_medium" time="0.000" classname="attribute.timeout"/>
  <testcase name="testcase_large" time="0.000" classname="attribute.timeout"/>
  <testcase name="testcase_new" time="0.297" classname="attribute.timeout">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method attribute.timeout.testcase_new() didn&#039;t finish within the time-out 200">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method attribute.timeout.testcase_new() didn't finish within the time-out 200
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.signalAll(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.tryTerminate(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- testcase_new -->
</testsuite> <!-- attribute.timeout -->
